baseURL: "https://www.avisblog.in/"
title: Avi's
paginate: 20
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-Y359N8SLR8

minify:
    disableXML: true
    minifyOutput: true

taxonomies:
  category: categories
  tag: tags

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Avi's Blog
    description: "A place where we share stories about Technology, Life Science and Books!"
    keywords: [Blog, Portfolio, PaperMod, Hugo, ]
    author: ["Winnie", "Zuha"]
    #images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    # assets:
    #     # disableHLJS: true # to disable highlight.js
    #     # disableFingerprinting: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # label:
    #     text: "Home"
    #     icon: /apple-touch-icon.png
    #     iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi \U0001F44B"
        Content: "Welcome to Avi's - A space where we share stories about the things we do, read and experience in life!" 
        Quote: "Great Stories happens to those who can tell them ~ Ira Glas"
        Content2: "Let's Make some great stories to happen"

    # socialIcons:
    #     - name: twitter
    #       url: "https://twitter.com/"
    #     - name: stackoverflow
    #       url: "https://stackoverflow.com"
    #     - name: github
    #       url: "https://github.com/"

    #analytics:
        #google:
            #SiteVerificationTag: "G-Y359N8SLR8"
        # bing:
        #     SiteVerificationTag: "XYZabc"
        # yandex:
        #     SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # editPost:
    #     URL: "https://github.com/<path_to_repo>/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: Tech
          name: Tech
          url: /categories/tech
          weight: 10

        - identifier: Biology
          name: Biology
          url: /categories/biology
          weight: 20

        - identifier: Aerospace
          name: Aerospace
          url: /categories/aerospace
          weight: 30

        - identifier: Books
          name: Books
          url: /categories/books
          weight: 40

        
        # - identifier: tags
        #   name: tags
        #   url: /tags/
        #   weight: 20
        # - identifier: example
        #   name: example.org
        #   url: https://example.org
        #   weight: 30
          
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
